export const ACTION_BOOKS_LOADED = 'ACTION_BOOKS_LOADED';
export const ACTION_BOOK_CREATED = 'ACTION_BOOK_CREATED';
export const ACTION_BOOK_UPDATED = 'ACTION_BOOK_UPDATED';
export const ACTION_BOOK_SELECT = 'ACTION_BOOK_SELECT';
export const ACTION_ED_STATE = 'ACTION_ED_STATE';